server:
    port: 9001
spring:
    application:
        name: eureka-server

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${container.eureka.url:localhost}:9001/eureka
    server:
        wait-time-in-ms-when-sync-empty: 0

