server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: scheduler_service_route
              uri: lb://scheduler_service
              predicates:
                - Path=/serv/**
              filters:
                - RewritePath=/serv/(?<remaining>.*), /$\{remaining}

eureka:
  client:
    service-url:
      defaultZone: http://${container.eureka.url:localhost}:9001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    preferIpAddress: true

container:
  eureka:
    url: eureka-server